### ISSUE TITLE
ANSI -> UTF-8

### ISSUE THREAD

**Issue by tpiechowiak** [oscar-broman/strlib#14]
I'm trying to encode message from server, ANSI -> UTF8 for discord-connector. Message contains polish letters and with ŁASDAŚĄŁŚLD I'm getting £ASDA¥£LD on discord using the newest version

utf8encode(dest, text); and text is inputed text by player
the same with decoding message  received from discord

**Comment by daxon852aa** [comment]
you must knock down a horse

**Comment by daxon852aa** [comment]
I would like to know that too, help us ...

**Comment by daxon852aa** [comment]
![image](https://user-images.githubusercontent.com/33399395/56616415-a16ef900-661d-11e9-9d8c-7fb555a49c31.png)

**Comment by oscar-broman** [comment]
For Polish text, the character set used is ISO 8859-2 (Latin-2).
The utf8 encode/decode functions assume ISO-8859-1 (Latin-1).

You’d need other decode/encode functions for Polish text.

**Comment by marihunaen** [comment]
Can you recode it to Latin-2? If so, will you do it for me? I would be really grateful :)

**Comment by blasty852** [comment]
Hello Oscar,

I would only like to ask you, if you are planning or working on this extension for Latin-2. Our community is pretty big and for security reasons, we need to implement a tool, that requires certain characters from our language to be shown. Multiple people from my administration have pointed out on this include, however after multiple testings it did not work until I just read, what is written here and understood, that it only supports Latin-1 version.

I know it might be time consuming and if that is the reason, I am also willing to pay you desired amount of money, because it is really important for us and that's where our whole security lies so I am afraid, that we will not be able to run for much longer, if we do not implement this feature.

For any response from your side, I will be more than thankful!

Cheers.

**Comment by oscar-broman** [comment]
Right, I think there's some clarification needed.

The utf-8 encode/decode functions only convert between unicode arrays and unicode expressed as utf-8.

When you say it only supports Latin-1, that's _sort of_ true. It just happens to be that latin-1 and unicode have the same characters in the range 0x00-0xFF. As such, unless you actually give unicode to be encoded as utf-8, you'll get badly encoded characters.

So what's really needed is a way to convert from/to unicode. There is no such functionality in strlib, but you should be able to create it quite easily.

https://en.wikipedia.org/wiki/ISO/IEC_8859-2

See the table on that Wikipedia page. Now let's take an example:
C8, which is the letter *Č*. Its Unicode codepoint is not the same as its 8859-2 (Latin-2) codepoint. Instead of being 0xC8 in Unicode, it should be 0x10C.

So if you want to encode something *to* Unicode, you need to change the codepoint 0xC8 to 0x10C and then run `utf8_encode` to get the Unicode string encoded as UTF-8.
If you want to convert *from* Unicode, use `utf8_decode` then convert 0x10C to 0xC8.

You need to make a function that converts between these codepoints to make a character encoding conversion.

**Comment by oscar-broman** [comment]
This may help: https://github.com/winlibs/libiconv/blob/master/source/lib/iso8859_2.h

**Comment by blasty852** [comment]
Is there any way you could help us with it, since till now I did not manage to figure out, how to add those special encodings from that wikipedia page.

**Comment by oscar-broman** [comment]
If you convert that link I sent into Pawn, then you should be able to do the conversion. It should be fairly straightfoward. I don't have Pawn installed and I haven't written code in it for many years so I don't think I can be very helpful in that.

**Comment by blasty852** [comment]
I spent last 2 hours trying to understand various tutorials about bit operators, but for some reason (maybe I am really stupid) I just can not fathom it. Maybe if some skilled programmer just sat next to me and explained it to me IRL, I would but... that is quite unreal now due to the situation and whatnot. So you are saying, that from the provided script "iso8859_2.h" is a function, that could do the conversion?

Because the way the function is written is completely different from the way you wrote it in strlib. When I compare characters in the wikipedia page with this "iso8859_2.h" script, I actually see some matches such as that alphabet "A,B,C,D,E,F" cathegories, but when I tried to imply it into utf8_encode function, I only saw things like "0b11111100", which completely messed me up.

So lets say I take array:
static const unsigned short iso8859_2_2uni
that contains these characters, I put it at the tope of my gamemode - clear till now.

Now does this function:
iso8859_2_mbtowc (conv_t conv, ucs4_t *pwc, const unsigned char *s, size_t n)

do basically the same, than utf8_encode, but it is just written differently? Because function utf8_encode did what I needed, except few of those characters just like you said for eg. "Č", that are not contained in the Latin-1 charset.

I will most likely figure out how to exchange those function parameters, but the code inside the iso8859_2_mbtowc function seems just to be sooo different from the code, you used to calculate the encoding in utf8_encode function. I hope you understand what I mean.

Thanks for you time!
